---
- name: Adicionar o usuário ao grupo Docker
  hosts: gbessa_hosts
  become: yes
  tasks:
    - name: Verificar se o grupo docker existe
      ansible.builtin.group:
        name: docker
        state: present
      register: group_check

    - name: Criar o grupo Docker se não existir
      ansible.builtin.group:
        name: docker
        state: present
      when: group_check.changed

    - name: Adicionar o usuário ao grupo Docker
      ansible.builtin.shell: "usermod -aG docker $USER"
    
    - name: Atualizar o grupo do usuário para docker
      ansible.builtin.shell: "newgrp docker"