---
- name: Configuração Básica com Role
  hosts: gbessa_hosts
  become: true  # Permissão de sudo
  roles:
    - common

- name: Remover pacotes e repositório Docker de Debian
  hosts: gbessa_hosts
  become: yes
  tasks:
    - name: Remover pacotes Docker antigos
      ansible.builtin.shell: |
        for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do
          sudo apt-get remove -y $pkg
        done
      ignore_errors: yes

    - name: Remover o arquivo do repositório Docker
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Remover a chave GPG do Docker
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.asc
        state: absent

    - name: Atualizar repositórios APT após remoção
      ansible.builtin.apt:
        update_cache: yes


- name: Instalar Docker em Ubuntu
  hosts: gbessa_hosts
  become: yes
  tasks:
    - name: Atualizar repositórios APT
      ansible.builtin.apt:
        update_cache: yes

    - name: Instalar ca-certificates e curl
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Criar diretório para as chaves do APT
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Baixar chave GPG do Docker
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Ajustar permissões da chave GPG
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Adicionar o repositório Docker à lista de fontes do APT
      ansible.builtin.shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$UBUNTU_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /etc/apt/sources.list.d/docker.list

    - name: Atualizar novamente os repositórios APT
      ansible.builtin.apt:
        update_cache: yes

    - name: Instalar pacotes do Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present